package org.alkemy.campus.disney.core.db;

import java.io.Serializable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import com.google.gson.Gson;

@MappedSuperclass
public class PersitentEntity implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * Obtains the entity's database-identification property.
     * 
     * @return the autogenerated ID value
     */
    public Long getId() {
        return id;
    }

    public PersitentEntity setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }
}
